services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    networks: 
      - app-networks
    depends_on:
      - db
    env_file:
      - ./api/.env

  db:
    image: postgres
    container_name: postgres
    networks:
      - app-networks
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - ./.env

  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    container_name: listener
    restart: unless-stopped
    volumes:
      - ./listener:/app
    networks:
      - app-networks
    depends_on:
      - api
    env_file:
      - ./listener/.env

  history:
    build:
      context: ./history  # Directorio donde se encuentra tu Dockerfile y código para history
      dockerfile: Dockerfile  # Nombre del Dockerfile en el directorio ./history
    container_name: history  # Nombre del contenedor
    restart: unless-stopped
    volumes:
      - ./history:/app  # Volumen que mapea el código de history
    networks:
      - app-networks
    depends_on:
      - api  # Este servicio depende del servicio api
    env_file:
      - ./history/.env  # Archivo de variables de entorno para el servicio history

  requests:
    build:
      context: ./request
      dockerfile: Dockerfile
    container_name: request
    restart: unless-stopped
    volumes:
      - ./request:/app
    ports:
      - "8000:8000"
    networks:
      - app-networks
    depends_on:
      - api
    env_file:
      - ./request/.env
  
  validations:
    build:
      context: ./validations
      dockerfile: Dockerfile
    container_name: validations
    restart: unless-stopped
    volumes:
      - ./validations:/app
    ports:
      - "9000:9000"
    networks:
      - app-networks
    depends_on:
      - api
    env_file:
      - ./validations/.env

networks:
  app-networks:
    driver: bridge

volumes:
  db-volume:

